Repository project-owlly/site, pull requests merged in 2020-10, with the labels that each got.

#47 microsite mit return funktion
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/pages/infosite/infosite.page.html
  src/app/pages/infosite/infosite.page.ts
  src/app/pages/return/return.page.ts
  src/app/services/oidc.service.spec.ts
  src/app/services/oidc.service.ts
Labels: enhancement

#48 Html description
  src/app/pages/home/home.page.html
  src/index.html
Labels: documentation

#53 fix: userdata in html template
  src/app/pages/return/return.page.html
Labels: bug

#57 Add owlly
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/pages/infosite/infosite.page.html
  src/main.ts
Labels: enhancement

#69 feat angular universal
  .browserslistrc
  angular.json
  e2e/tsconfig.json
  package-lock.json
  package.json
  server.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/app.server.module.ts
  src/main.server.ts
  src/main.ts
  tsconfig.app.json
  tsconfig.base.json
  tsconfig.json
  tsconfig.server.json
  tsconfig.spec.json
Labels: enhancement

#90 mockdata
  src/app/services/pdf-service.service.ts
Labels: enhancement

#91 Newsletter improvement
  src/app/components/footer/footer.component.scss
  src/app/pages/feedback/feedback.page.html
  src/app/pages/feedback/feedback.page.scss
  src/app/pages/home/home.page.html
  src/app/pages/home/home.page.scss
  src/app/pages/impressum/impressum.page.html
  src/app/pages/impressum/impressum.page.scss
  src/app/pages/infosite/infosite.page.html
  src/app/pages/infosite/infosite.page.scss
  src/app/pages/infosite/infosite.page.ts
  src/app/pages/newsletter/newsletter.module.ts
  src/app/pages/newsletter/newsletter.page.html
  src/app/pages/newsletter/newsletter.page.scss
  src/app/pages/return/return.page.ts
  src/app/services/owlly.service.ts
  src/assets/eule.png
  src/global.scss
Labels: enhancement

#99 style: owlly-sign active
  src/app/pages/infosite/infosite.page.html
  src/app/pages/infosite/infosite.page.scss
Labels: enhancement

#100 github icon
  src/app/pages/home/home.page.html
  src/assets/icon/facebook.png
  src/assets/icon/facebook.svg
  src/assets/icon/facebookIcon.png
  src/assets/icon/facebook_margin.png
  src/assets/icon/instagram.png
  src/assets/icon/instagram.svg
  src/assets/icon/twitter.png
  src/assets/icon/twitter.svg
  src/assets/icon/youtube.png
  src/assets/socialmedia/facebook.svg
  src/assets/socialmedia/github.svg
  src/assets/socialmedia/instagram.svg
  src/assets/socialmedia/twitter.svg
  src/assets/socialmedia/youtube.svg
Labels: enhancement

#105 feat: pwa
  angular.json
  ngsw-config.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/assets/icon/android-chrome-192x192.png
  src/assets/icon/android-chrome-384x384.png
  src/assets/icon/apple-touch-icon.png
  src/assets/icon/favicon-16x16.png
  src/assets/icon/favicon-32x32.png
  src/assets/icon/favicon.ico
  src/assets/icon/mstile-150x150.png
  src/assets/icon/safari-pinned-tab.svg
  src/assets/icon/site.webmanifest
  src/assets/icons/android-chrome-192x192.png
  src/assets/icons/android-chrome-512x512.png
  src/assets/icons/apple-touch-icon.png
  src/assets/icons/browserconfig.xml
  src/assets/icons/favicon-16x16.png
  src/assets/icons/favicon-32x32.png
  src/assets/icons/favicon.ico
  src/assets/icons/icon-default-192x192.png
  src/assets/icons/icon-default-512x512.png
  src/assets/icons/mstile-150x150.png
  src/index.html
  src/manifest.webmanifest
Labels: enhancement

#106 feat: social meta tags
  src/assets/meta/owlly-meta.png
  src/index.html
Labels: enhancement

#107 feat: load google fonts
  src/assets/fonts/lato-v17-latin-900.eot
  src/assets/fonts/lato-v17-latin-900.svg
  src/assets/fonts/lato-v17-latin-900.ttf
  src/assets/fonts/lato-v17-latin-900.woff
  src/assets/fonts/lato-v17-latin-900.woff2
  src/assets/fonts/lato-v17-latin-regular.eot
  src/assets/fonts/lato-v17-latin-regular.svg
  src/assets/fonts/lato-v17-latin-regular.ttf
  src/assets/fonts/lato-v17-latin-regular.woff
  src/assets/fonts/lato-v17-latin-regular.woff2
  src/global.scss
  src/theme/fonts.scss
Labels: enhancement

#108 fix: text area
  src/app/pages/feedback/feedback.page.html
  src/app/pages/feedback/feedback.page.scss
  src/app/pages/newsletter/newsletter.page.html
  src/app/pages/newsletter/newsletter.page.scss
  src/app/pages/newsletter/newsletter.page.ts
Labels: bug
